### ISSUE TITLE
Questions about the function in warp_field.cpp

### ISSUE THREAD

**Issue by Desperater** [mihaibujanca/dynamicfusion#20]
Hi Mihai,
I've been work on your project for several days but I can't get a satisfied result. I found some functions in warp_field.cpp is not implemented , and the function WarpField::energy_data() really cost too much time. Can you give some ideas for what I can do to speed it up?
 In Dynamic Fusion paper the equation 6 is not detailed and I wonder whether it is a nonlinear least square problems? Equation 6 is mainly want to estimate the transformation dgse3 ,but what is the difference between the dgse3 and the se3 that the frame-to-frame ICP get?
Thank you!

**Comment by mihaibujanca** [comment]
Hi, I'm working on speeding up energy data, but don't yet have an eta - I'm currently trying to use Opt (https://github.com/niessner/Opt) for it, and if that won't give satisfying results, I will need to try to write everything in CUDA to get it working on the GPU.

It will definitely need to run on a GPU to be able to have a decent speed. The optimisation is computing ~1.5M variables per frame, there's no way to do that fast on a CPU.

**Short answer** for the two se3: the frame-to-frame ICP is for pose estimation, dg_se is for non-rigid deformations.

**longer answer**:
The warp field has 3 components for each node: `dg_v, dg_w, dg_se`. `dg_se` is a per-node transformation that transformes `dg_v` into the live frame. The frame-to-frame ICP is estimating a rigid transformation in order to account for camera pose changes.

**Comment by Desperater** [comment]
Thank you for your answers! Looking forward to your new versions.

**Comment by mihaibujanca** [comment]
Can this be closed now?

**Comment by Desperater** [comment]
sorry ，it's my first time to use github. I will close it right now.
